const users = [
  { id: 1, username: 'John', age: 23 },
  { id: 2, username: 'Alice', age: 30 },
  { id: 3, username: 'Bob', age: 28 },
  { id: 4, username: 'Ella', age: 35 },
  { id: 5, username: 'David', age: 29 },
  { id: 6, username: 'Sophia', age: 27 },
  { id: 7, username: 'Oliver', age: 22 },
  { id: 8, username: 'Emma', age: 25 },
  { id: 9, username: 'Liam', age: 26 },
  { id: 10, username: 'Grace', age: 32 },
  { id: 11, username: 'Lucas', age: 31 },
  { id: 12, username: 'Mia', age: 24 },
  { id: 13, username: 'Noah', age: 27 },
  { id: 14, username: 'Ava', age: 29 },
  { id: 15, username: 'William', age: 34 },
  { id: 16, username: 'Emily', age: 26 },
  { id: 17, username: 'James', age: 33 },
  { id: 18, username: 'Charlotte', age: 28 },
  { id: 19, username: 'Benjamin', age: 30 },
  { id: 20, username: 'Harper', age: 25 },
  { id: 21, username: 'Henry', age: 29 },
  { id: 22, username: 'Evelyn', age: 27 },
  { id: 23, username: 'Michael', age: 32 },
  { id: 24, username: 'Abigail', age: 31 },
  { id: 25, username: 'Alexander', age: 33 },
];

module.exports = users;
